name: Deploy to Vultr

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Vultr
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VULTR_HOST }}
        username: ${{ secrets.VULTR_USERNAME }}
        key: ${{ secrets.VULTR_SSH_KEY }}
        script: |
          cd sg-vite
          git pull
          docker run --rm -v $(pwd):/app -v /home/kawa/.npm:/.npm -w /app -u $(id -u):$(id -g) node:16-slim npm run build
